apiVersion: v2
name: neohoods-portal-chart
description: A Helm chart for deploying NeoHoods portal app
type: application
version: 0.1.208
appVersion: "1.0.1"
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
