{{- if .Values.backend.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: portal-{{ .Release.Name }}-backend
spec:
  type: {{ .Values.backend.service.type | default "ClusterIP" }}
  selector:
    app: portal-{{ .Release.Name }}-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http-server
      {{- if eq (.Values.backend.service.type | default "ClusterIP") "NodePort" }}
      nodePort: {{ .Values.backend.service.nodePort }}
      {{- end }}
{{- end }}