{{- if and .Values.backend.enabled .Values.backend.debug.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: portal-{{ .Release.Name }}-backend-debug
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  type: {{ .Values.backend.service.type | default "ClusterIP" }}
  selector:
    app: portal-{{ .Release.Name }}-backend
  ports:
    - name: debug
      protocol: TCP
      port: 5005
      targetPort: debug
      {{- if eq (.Values.backend.service.type | default "ClusterIP") "NodePort" }}
      nodePort: {{ .Values.backend.service.nodePortForDebug }}
      {{- end }}

{{- end }} 