apiVersion: batch/v1
kind: Job
metadata:
  name: portal-{{ .Release.Name }}-flyway
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: portal-{{ .Release.Name }}-flyway
          image: "{{ .Values.flyway.image.repository }}:{{ .Values.flyway.image.tag }}"
          args: ["-connectRetries=60", "migrate", "-locations=filesystem:/flyway/sql-init,filesystem:/flyway/sql-v2,filesystem:/flyway/sql-v3{{- if .Values.flyway.fakeData }},filesystem:/flyway/sql-fake-data{{- end }}{{- if .Values.flyway.customInitData.enabled }},filesystem:{{ .Values.flyway.customInitData.mountPath }}{{- end }}"]
          env:
            - name: FLYWAY_USER
              value: "{{ .Values.postgresql.auth.username }}"
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.postgresql.auth.existingSecret }}"
                  key: "{{ .Values.postgresql.auth.secretKeys.userPasswordKey }}"
            - name: FLYWAY_URL
              value: "jdbc:postgresql://{{ .Values.global.chatName }}-postgresql.{{ .Values.global.namespace }}.svc.cluster.local:5432/{{ .Values.postgresql.auth.database }}"
            - name: FLYWAY_BASELINE_ON_MIGRATE
              value: "true"
            - name: FLYWAY_CLEAN_DISABLED
              value: "true"
          volumeMounts:
            - name: sql-init
              mountPath: /flyway/sql-init
            - name: sql-v2
              mountPath: /flyway/sql-v2
            - name: sql-v3
              mountPath: /flyway/sql-v3
            {{- if .Values.flyway.fakeData }}
            - name: sql-fake-data
              mountPath: /flyway/sql-fake-data
            {{- end }}
            {{- if .Values.flyway.customInitData.enabled }}
            - name: custom-init-data
              mountPath: {{ .Values.flyway.customInitData.mountPath }}
            {{- end }}
      volumes:
        - name: sql-init
          configMap:
            name: portal-{{ .Release.Name }}-flyway-sql-init
        - name: sql-v2
          configMap:
            name: portal-{{ .Release.Name }}-flyway-sql-v2
        - name: sql-v3
          configMap:
            name: portal-{{ .Release.Name }}-flyway-sql-v3
        {{- if .Values.flyway.fakeData }}
        - name: sql-fake-data
          configMap:
            name: portal-{{ .Release.Name }}-flyway-sql-fake-data
        {{- end }}
        {{- if .Values.flyway.customInitData.enabled }}
        - name: custom-init-data
          configMap:
            name: {{ .Values.flyway.customInitData.configMapName }}
        {{- end }}
      restartPolicy: Never
