{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: portal-{{ .Release.Name }}-frontend
  labels:
    app: portal-{{ .Release.Name }}-frontend
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  selector:
    app: portal-{{ .Release.Name }}-frontend
  ports:
    - port: 80
      targetPort: http-server
      {{- if eq (.Values.frontend.service.type | default "ClusterIP") "NodePort" }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
{{- end }}