{{- if .Values.flyway.customInitData.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.flyway.customInitData.configMapName }}
  labels:
    app: portal-{{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: portal-{{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if .Values.flyway.customInitData.files }}
{{- range .Values.flyway.customInitData.files }}
  {{ .name }}: |-
{{- if .content }}
{{ .content | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
